### ISSUE TITLE
DSM version 7

### ISSUE THREAD

**Issue by jarugut** [seba76/phpvirtualbox4dsm#4]
Thank you for your great job with the current compilations for DSM 6.2.
Do you have in project compile the current virtual box to be able to use in DSM7?

**Comment by seba76** [comment]
Not at the moment. Synology changed packaging format so it is not trivial task. But if you need it you can install it as any other web site. Just make sure to enable PHP and web server on your DSM.  You can download latest phpVirtualBox from their repo [here](https://github.com/phpvirtualbox/phpvirtualbox/). This requires manual configuration of config.php.

**Comment by jarugut** [comment]
thank you for your answer. I mean more for the virtualbox package than the phpvirtualbox, like you say theoretically could be possible to deploy like a normal web server.

**Comment by seba76** [comment]
I assumed you asked about this package since you made issue here. Issue about DSM 7 version already exists in virtualbox4dsm repo [virtualbox4dsm on DSM 7](https://github.com/seba76/virtualbox4dsm/issues/21) and I assumed you wouldn't be asking the same question again.

**Comment by jarugut** [comment]
Thank you Seba and sorry for the misunderstanding.
